# Generated by Django 5.1.3 on 2024-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='point',
            new_name='coordinates',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
