# Generated by Django 5.1.3 on 2024-11-29 12:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_task_rename_coordinates_location_center_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('feed', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('bedroom_count', models.PositiveIntegerField(blank=True, null=True)),
                ('review_score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('usd_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('images', models.JSONField(default=list)),
                ('amenities', models.JSONField(default=list)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
