# Generated by Django 5.1.3 on 2024-11-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizeAccommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('policy', models.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='tasks.accommodation')),
            ],
        ),
    ]
