# Generated by Django 5.1.3 on 2024-12-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_localizeaccommodation'),
    ]

    operations = [
    ]
